# Generated by Django 6.0.4 on 2026-07-23 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_constraints_and_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('CLIENTE', 'Cliente'), ('VENDEDOR', 'Vendedor')], default='CLIENTE', max_length=20),
        ),
    ]
